name: notes.kargware-icon-font

on:
  push:
    branches:
      - gh-pages
      - master
      
env:
  SVG_DIR: svgs
  DIST_DIR: dist

jobs:
  webfont-generation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      # Checkout the code
      - uses: actions/checkout@v2
      
      - name: Create Folders
        run: |
          make create-folders DIST_DIR=$DIST_DIR SVG_DIR=$SVG_DIR
          ls -lR $DIST_DIR

      # https://docs.github.com/en/actions/guides/building-and-testing-nodejs
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install `icon-font-generator` via npm
        run: make install-font-generator
        
      - name: Collect / Download the SVGs
        run: make collect-svgs SVG_DIR=$SVG_DIR
      
      - name: Generate Webfont
        run: make generate-font SVG_DIR=$SVG_DIR

      - name: Archive artifacts - fonts only
        uses: actions/upload-artifact@v2
        with:
          name: fonts-only
          path: |
            dist/fonts
            !**/*.css
            !**/*.html
            !**/*.svg
          retention-days: 14

      - name: Archive artifacts - dist
        uses: actions/upload-artifact@v2
        with:
          name: notes.kargware-icon-font
          path: |
            dist
          retention-days: 14
          
      # - name: Deploy as GitHub Page
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: ./$DIST_DIR
      #    # publish_dir: ./dist
      
      - name: Deploy as GitHub Page 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.

      ## https://github.com/actions/create-release
      ## https://github.com/softprops/action-gh-release
      #- name: Create Release
      #  id: create_release
      #  uses: actions/create-release@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    tag_name: ${{ github.ref }}
      #    release_name: Release ${{ github.ref }}
      #    if: startsWith(github.ref, 'refs/tags/')
      #    body: |
      #      Changes in this Release
      #      - Initial commit
      #      - Setup the pipeline
      #      - Keep the artifacts
      #    draft: false
      #    prerelease: false
